"""Data loader for pre-computed StereoSet evaluation results.

Reads model-specific JSON files and caches them so the dashboard can
access scores, examples, and head sensitivity data without reloading.
GUS-NET JSON files: stereoset_precomputed_gusnet.json (BERT) and
stereoset_precomputed_gusnet_gpt2.json (GPT-2).

Files:
    stereoset_precomputed_bert.json  — BERT PLL scoring
    stereoset_precomputed_gpt2.json  — GPT-2 autoregressive scoring
"""

import json
from pathlib import Path
from typing import Dict, List, Optional

_DATA_DIR = Path(__file__).parent

# Per-model cache
_cache: Dict[str, dict] = {}

# Map base model names and GUS-Net keys to our short model key
_MODEL_KEY_MAP = {
    # Short keys
    "bert": "bert",
    "bert_large": "bert_large",
    "gpt2": "gpt2",
    "gpt2_medium": "gpt2_medium",
    # Full HuggingFace model names
    "bert-base-uncased": "bert",
    "bert-large-uncased": "bert_large",
    "gpt2-medium": "gpt2_medium",
    # GUS-Net model keys
    "gusnet-bert": "bert",
    "gusnet-bert-large": "bert_large",
    "gusnet-bert-custom": "bert",
    "gusnet-ensemble": "bert",
    "gusnet-gpt2": "gpt2",
    "gusnet-gpt2-medium": "gpt2_medium",
}

_FILE_MAP = {
    "bert": "stereoset_precomputed_bert.json",
    "bert_large": "stereoset_precomputed_bert_large.json",
    "gpt2": "stereoset_precomputed_gpt2.json",
    "gpt2_medium": "stereoset_precomputed_gpt2_medium.json",
    # GUS-NET variants (generated by stereoset_gusnet_*_analysis.ipynb)
    "gusnet_bert": "stereoset_precomputed_gusnet_bert.json",
    "gusnet_bert_large": "stereoset_precomputed_gusnet_bert_large.json",
    "gusnet_gpt2": "stereoset_precomputed_gusnet_gpt2.json",
    "gusnet_gpt2_medium": "stereoset_precomputed_gusnet_gpt2_medium.json",
}

# Fallback filenames (old names generated by notebook before renaming convention)
_FILE_MAP_FALLBACKS = {
    "gusnet_bert": "stereoset_precomputed_gusnet.json",
}

# Map a resolved base key to its GUS-NET counterpart
_GUSNET_KEY_MAP = {
    "bert": "gusnet_bert",
    "bert_large": "gusnet_bert_large",
    "gpt2": "gusnet_gpt2",
    "gpt2_medium": "gusnet_gpt2_medium",
}


def get_gusnet_key(base_key: str) -> str:
    """Return the GUS-NET variant key for a given base model key."""
    return _GUSNET_KEY_MAP.get(base_key, "gusnet_bert")


def _resolve_key(model: Optional[str]) -> str:
    """Resolve any model identifier to a canonical file key.

    Keys that are already in _FILE_MAP (e.g. 'gusnet_bert') are returned
    as-is so they can be looked up directly without being remapped.
    """
    if model is None:
        return "bert"
    # If the key is already a known file key, pass it through unchanged
    if model in _FILE_MAP:
        return model
    return _MODEL_KEY_MAP.get(model, "bert")


def load_stereoset_data(model: Optional[str] = None) -> Optional[dict]:
    """Load and cache the pre-computed StereoSet JSON for a model.

    Parameters
    ----------
    model : str or None
        Any model identifier: 'bert', 'gpt2', a HuggingFace model name,
        or a GUS-Net key.  Defaults to 'bert'.

    Returns None if the file does not exist (script hasn't been run yet).
    """
    key = _resolve_key(model)

    if key in _cache:
        return _cache[key]

    filepath = _DATA_DIR / _FILE_MAP.get(key, _FILE_MAP["bert"])
    # Try fallback filename if the primary file doesn't exist (e.g. old notebook output name)
    if not filepath.exists() and key in _FILE_MAP_FALLBACKS:
        filepath = _DATA_DIR / _FILE_MAP_FALLBACKS[key]
    if not filepath.exists():
        return None

    with open(filepath, "r", encoding="utf-8") as f:
        _cache[key] = json.load(f)
    return _cache[key]


def get_stereoset_scores(model: Optional[str] = None) -> Optional[Dict]:
    """Return overall + per-category SS/LMS/ICAT scores."""
    data = load_stereoset_data(model)
    if data is None:
        return None
    return data.get("scores")


def get_stereoset_examples(
    model: Optional[str] = None,
    category: Optional[str] = None,
) -> List[Dict]:
    """Return StereoSet examples, optionally filtered by category."""
    data = load_stereoset_data(model)
    if data is None:
        return []
    examples = data.get("examples", [])
    if category:
        examples = [e for e in examples if e["category"] == category]
    return examples


def get_head_sensitivity_matrix(model: Optional[str] = None) -> Optional[List[List[float]]]:
    """Return the 12×12 head sensitivity variance matrix."""
    data = load_stereoset_data(model)
    if data is None:
        return None
    return data.get("head_sensitivity_matrix")


def get_sensitive_heads(model: Optional[str] = None) -> List[Dict]:
    """Return the top-10 most sensitive heads."""
    data = load_stereoset_data(model)
    if data is None:
        return []
    return data.get("sensitive_heads", [])


def get_top_features(model: Optional[str] = None) -> List[Dict]:
    """Return top-20 most discriminative features by Kruskal-Wallis p-value."""
    data = load_stereoset_data(model)
    if data is None:
        return []
    return data.get("top_features", [])


def get_head_profile_stats(model: Optional[str] = None) -> Optional[Dict]:
    """Return population statistics for each sensitive head's best feature.

    Returns None for old JSON format that lacks this field (graceful degradation).
    """
    data = load_stereoset_data(model)
    if data is None:
        return None
    return data.get("head_profile_stats")


def get_metadata(model: Optional[str] = None) -> Optional[Dict]:
    """Return metadata dict (model, date, counts)."""
    data = load_stereoset_data(model)
    if data is None:
        return None
    return data.get("metadata")
